### ISSUE TITLE
Bugs when using sniper mode

### ISSUE THREAD

**Issue by henry-lp** [SpoonLabs/sorald#119]
Here is to keep a collection of sniper mode bug before submitting to spoon.

**Comment by henry-lp** [comment]
When repairing with rule 1656, if the SNIPER mode is on. The diff looks nice but it will add a variable already existed causing duplicated field declarations (Output below, `int c` is declared twice) . 
```
diff --git a/testcases/SelfAssignement.java b/testcases/SelfAssignement.java
index a3ccbed..03805c8 100644
--- a/testcases/SelfAssignement.java
+++ b/testcases/SelfAssignement.java
@@ -1,11 +1,12 @@
 class SelfAssignement {
   int a,c = 0;
+
+       int c = 0;
   int[] b = {0};
   int h = 0;
   int[] g = 0;
   SelfAssignementCheckB checkB = new SelfAssignementCheckB();
   void method(int e,int h) {
-    a = a; // Noncompliant [[sc=7;ec=8]] {{Remove or correct this useless self-assignment.}}
     this.a = this.a; // Noncompliant
     b[0] = b[0]; // Noncompliant
     b[fun()] = b[fun()]; // Noncompliant
```
Is there a way to disable this function or we have to in general avoid declaration like these ` int a,c = 0;` ? 

@monperrus  @fermadeiral

**Comment by henry-lp** [comment]
Code smell rule 1948 is buggy in Jenkins Context . I got this error when Sorald try to output the file with JavaOutputProcessor. All other rules work fine . 

```
spoon.SpoonException: Inconsistent sourceFragmentContextStack
	at spoon.support.sniper.SniperJavaPrettyPrinter.runInContext(SniperJavaPrettyPrinter.java:429)
	at spoon.support.sniper.SniperJavaPrettyPrinter.calculate(SniperJavaPrettyPrinter.java:112)
	at spoon.support.JavaOutputProcessor.createJavaFile(JavaOutputProcessor.java:116)
	at spoon.support.JavaOutputProcessor.process(JavaOutputProcessor.java:152)
	at sorald.DefaultRepair.repair(DefaultRepair.java:77)
	at sorald.Main.start(Main.java:137)
	at sorald.Main.main(Main.java:143)
	at fr.inria.spirals.repairnator.process.step.repair.Sorald.businessExecute(Sorald.java:67)
	at fr.inria.spirals.repairnator.process.step.AbstractStep.execute(AbstractStep.java:336)
	at fr.inria.spirals.repairnator.process.step.repair.AbstractRepairStep.execute(AbstractRepairStep.java:62)
	at fr.inria.spirals.repairnator.process.step.AbstractStep.executeNextStep(AbstractStep.java:188)
	at fr.inria.spirals.repairnator.process.step.AbstractStep.execute(AbstractStep.java:353)
	at fr.inria.spirals.repairnator.process.step.AbstractStep.executeNextStep(AbstractStep.java:188)
	at fr.inria.spirals.repairnator.process.step.AbstractStep.execute(AbstractStep.java:353)
	at fr.inria.spirals.repairnator.process.inspectors.components.RunInspector4DefaultGit.run(RunInspector4DefaultGit.java:104)
	at fr.inria.spirals.repairnator.process.inspectors.ProjectInspector.run(ProjectInspector.java:305)
	at fr.inria.spirals.repairnator.pipeline.GithubMainProcess.run(GithubMainProcess.java:126)
	at fr.inria.spirals.repairnator.pipeline.BranchLauncher.main(BranchLauncher.java:97)
	at fr.inria.spirals.repairnator.pipeline.BranchLauncher.launch(BranchLauncher.java:103)
	at fr.inria.spirals.repairnator.pipeline.Launcher.main(Launcher.java:70)
```

**Comment by monperrus** [comment]
> Is there a way to disable this function or we have to in general avoid declaration like these ` int a,c = 0;` ? 

That's the same bug as what Fernanda reported in https://github.com/INRIA/spoon/issues/3386

1. We already have a workaround for fields in master and the latest beta release
1. I'll do the same workaround for local variables
1. I'm working on a fully-working fix

**Comment by fermadeiral** [comment]
> [...] All other rules work fine .

Work fine when you are doing what? My investigation using our test cases, which are supposed to be simple stuff, shows a different conclusion. Note that a problem does not only exist when an exception occur. I found some repairs that are actually printed wrongly by the sniper printer and no exception occurs, which is somewhat worse (I would prefer not to deliver patch at all than to deliver a wrong patch for the users).

**Comment by monperrus** [comment]
Workaround for local variables: https://github.com/INRIA/spoon/pull/3398

**Comment by fermadeiral** [comment]
@henry-lp, will you report the issue with the code smell rule 1948 in Spoon?

For your info, I already reported a second issue: https://github.com/INRIA/spoon/issues/3399

Please, take a look at the link so you don't spend your time in something I already did like with the other issue.

**Comment by fermadeiral** [comment]
A third issue: https://github.com/INRIA/spoon/issues/3401

**Comment by fermadeiral** [comment]
@henry-lp, I suggest that, until tomorrow, we don't report any bug related to the sniper printer (neither here nor in Spoon), because some fixes were applied to Spoon, and I already saw that those fixes also fixed some issues that I haven't reported yet. My point is: some issues that we already saw might not exist anymore. I will wait for the next Spoon beta version (tomorrow), and then after I update it here we can proceed to find more issues (and to report them in the Spoon repository).

**Comment by henry-lp** [comment]
Yay, Great news ! .

**Comment by slarse** [comment]
I'm investigating sniper printer failures related to our current test cases. Right now, the processors related to the following checks are causing issues:

https://github.com/SpoonLabs/sorald/blob/2434d1d09812a40b3241adf942ad7b7bf4e0c824/src/test/java/sorald/processor/ProcessorTestHelper.java#L31-L35

I'm currently studying how the sniper printer works in order to try to narrow down why these processors cause crashes.
