### ISSUE TITLE
Warnings miner crashes if you try to analyze a directory that does not contain any .java files

### ISSUE THREAD

**Issue by slarse** [SpoonLabs/sorald#173]
```
INFO  0 source files to be analyzed
INFO  0/0 source files have been analyzed
java.lang.NullPointerException
	at org.sonar.java.checks.verifier.MultipleFilesJavaCheckVerifier.scanFiles(MultipleFilesJavaCheckVerifier.java:116)
	at org.sonar.java.checks.verifier.MultipleFilesJavaCheckVerifier.verify(MultipleFilesJavaCheckVerifier.java:91)
	at org.sonar.java.checks.verifier.MultipleFilesJavaCheckVerifier.verify(MultipleFilesJavaCheckVerifier.java:58)
	at sorald.sonar.RuleVerifier.analyze(RuleVerifier.java:44)
	at sorald.miner.MineSonarWarnings.extractWarnings(MineSonarWarnings.java:207)
	at sorald.miner.MineSonarWarnings.main(MineSonarWarnings.java:164)
```

**Comment by slarse** [comment]
This was solved when updating to sonar-java 6.9.0
