### ISSUE TITLE
Null pointer exception in repair mode

### ISSUE THREAD

**Issue by nharrand** [SpoonLabs/sorald#276]
Hi,

I got the following exception when running sorald in repair mode

```
java -jar /app/lib/sorald-1.1-SNAPSHOT-jar-with-dependencies.jar repair --fileOutputStrategy IN_PLACE --originalFilesPath ./ --ruleKeys 2111,2142,2272,2116,2184,2095,1860,1948,1854,1444,4973
```

on [symon](https://github.com/sethm/symon.git) comit id `655bbb3ab09721edfcb94da2f3d3f302f694270b` with sorald `417b17dd5ec6d1fa4f9aacd300194e3fc5c4f78e`

```
java.lang.NullPointerException
	at sorald.processor.ArrayHashCodeAndToStringProcessor.canRepair(ArrayHashCodeAndToStringProcessor.java:23)
	at sorald.processor.ArrayHashCodeAndToStringProcessor.canRepair(ArrayHashCodeAndToStringProcessor.java:13)
	at sorald.processor.SoraldAbstractProcessor.isToBeProcessed(SoraldAbstractProcessor.java:119)
	at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:71)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:170)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:143)
	at spoon.reflect.visitor.CtScanner.visitCtBlock(CtScanner.java:300)
	at spoon.support.reflect.code.CtBlockImpl.accept(CtBlockImpl.java:58)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:178)
	at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:68)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:170)
	at spoon.reflect.visitor.CtScanner.visitCtMethod(CtScanner.java:566)
	at spoon.support.reflect.declaration.CtMethodImpl.accept(CtMethodImpl.java:58)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:178)
	at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:68)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:170)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:143)
	at spoon.reflect.visitor.CtScanner.visitCtClass(CtScanner.java:336)
	at spoon.support.reflect.declaration.CtClassImpl.accept(CtClassImpl.java:58)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:178)
	at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:68)
	at spoon.support.QueueProcessingManager.process(QueueProcessingManager.java:118)
	at sorald.Repair.repairModelWithInitializedProcessor(Repair.java:174)
	at sorald.Repair.defaultRepair(Repair.java:117)
	at sorald.Repair.repair(Repair.java:101)
	at sorald.Repair.repair(Repair.java:90)
	at sorald.cli.Cli$RepairCommand.call(Cli.java:141)
	at sorald.cli.Cli$RepairCommand.call(Cli.java:50)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at sorald.Main.main(Main.java:7)
Exception in thread "main" java.lang.IllegalStateException: CLI exited non-zero
	at sorald.Main.main(Main.java:12)
```

**Comment by slarse** [comment]
This is caused by an insufficient null-check in `canRepair`. This:

```java
        if (candidate.getTarget() == null) {
            return false;
        }
```

Needs to be this:

```java
        if (candidate.getTarget() == null || candidate.getTarget().getType() == null) {
            return false;
        }
```

`null` is such a bother ...

**Comment by nharrand** [comment]
> `null` is such a bother ...

When do we rewrite sorald in kotlin ;-) ?
