### ISSUE TITLE
GreedyBestFitScanner crashes if `SoraldAbstractProcessor.canRepair` crashes

### ISSUE THREAD

**Issue by slarse** [SpoonLabs/sorald#278]
If a processor crashes in the `canRepair` method, the `GreedyBestFitScanner` crashes.

**Comment by slarse** [comment]
Crash in RDF4J:

```
sorald repair --original-files-path . --rule-keys 2184
INFO  3187 source files to be analyzed
INFO  3187/3187 source files have been analyzed
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 1
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:373)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at java.base/java.util.Collections$UnmodifiableList.get(Collections.java:1321)
	at sorald.processor.CastArithmeticOperandProcessor.getExpectedType(CastArithmeticOperandProcessor.java:79)
	at sorald.processor.CastArithmeticOperandProcessor.canRepair(CastArithmeticOperandProcessor.java:24)
	at sorald.processor.CastArithmeticOperandProcessor.canRepair(CastArithmeticOperandProcessor.java:14)
	at sorald.sonar.GreedyBestFitScanner.enter(GreedyBestFitScanner.java:77)
	at spoon.reflect.visitor.CtScanner.visitCtBinaryOperator(CtScanner.java:287)
	at spoon.support.reflect.code.CtBinaryOperatorImpl.accept(CtBinaryOperatorImpl.java:34)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:178)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:170)
	at spoon.reflect.visitor.CtScanner.visitCtBinaryOperator(CtScanner.java:291)
	at spoon.support.reflect.code.CtBinaryOperatorImpl.accept(CtBinaryOperatorImpl.java:34)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:178)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:170)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:143)
	at spoon.reflect.visitor.CtScanner.visitCtInvocation(CtScanner.java:505)
	at spoon.support.reflect.code.CtInvocationImpl.accept(CtInvocationImpl.java:46)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:178)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:170)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:143)
	at spoon.reflect.visitor.CtScanner.visitCtBlock(CtScanner.java:300)
	at spoon.support.reflect.code.CtBlockImpl.accept(CtBlockImpl.java:58)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:178)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:170)
	at spoon.reflect.visitor.CtScanner.visitCtIf(CtScanner.java:483)
	at spoon.support.reflect.code.CtIfImpl.accept(CtIfImpl.java:36)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:178)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:170)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:143)
	at spoon.reflect.visitor.CtScanner.visitCtBlock(CtScanner.java:300)
	at spoon.support.reflect.code.CtBlockImpl.accept(CtBlockImpl.java:58)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:178)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:170)
	at spoon.reflect.visitor.CtScanner.visitCtFor(CtScanner.java:464)
	at spoon.support.reflect.code.CtForImpl.accept(CtForImpl.java:40)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:178)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:170)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:143)
	at spoon.reflect.visitor.CtScanner.visitCtBlock(CtScanner.java:300)
	at spoon.support.reflect.code.CtBlockImpl.accept(CtBlockImpl.java:58)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:178)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:170)
	at spoon.reflect.visitor.CtScanner.visitCtFor(CtScanner.java:464)
	at spoon.support.reflect.code.CtForImpl.accept(CtForImpl.java:40)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:178)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:170)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:143)
	at spoon.reflect.visitor.CtScanner.visitCtBlock(CtScanner.java:300)
	at spoon.support.reflect.code.CtBlockImpl.accept(CtBlockImpl.java:58)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:178)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:170)
	at spoon.reflect.visitor.CtScanner.visitCtMethod(CtScanner.java:566)
	at spoon.support.reflect.declaration.CtMethodImpl.accept(CtMethodImpl.java:58)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:178)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:170)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:143)
	at spoon.reflect.visitor.CtScanner.visitCtClass(CtScanner.java:336)
	at spoon.support.reflect.declaration.CtClassImpl.accept(CtClassImpl.java:58)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:178)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:170)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:143)
	at spoon.reflect.visitor.CtScanner.visitCtPackage(CtScanner.java:656)
	at spoon.support.reflect.declaration.CtPackageImpl.accept(CtPackageImpl.java:89)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:178)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:170)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:143)
	at spoon.reflect.visitor.CtScanner.visitCtPackage(CtScanner.java:655)
	at spoon.support.reflect.declaration.CtPackageImpl.accept(CtPackageImpl.java:89)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:178)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:170)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:143)
	at spoon.reflect.visitor.CtScanner.visitCtPackage(CtScanner.java:655)
	at spoon.support.reflect.declaration.CtPackageImpl.accept(CtPackageImpl.java:89)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:178)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:170)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:143)
	at spoon.reflect.visitor.CtScanner.visitCtPackage(CtScanner.java:655)
	at spoon.support.reflect.declaration.CtPackageImpl.accept(CtPackageImpl.java:89)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:178)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:170)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:143)
	at spoon.reflect.visitor.CtScanner.visitCtPackage(CtScanner.java:655)
	at spoon.support.reflect.declaration.CtPackageImpl.accept(CtPackageImpl.java:89)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:178)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:170)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:143)
	at spoon.reflect.visitor.CtScanner.visitCtPackage(CtScanner.java:655)
	at spoon.support.reflect.declaration.CtPackageImpl.accept(CtPackageImpl.java:89)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:178)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:170)
	at spoon.reflect.visitor.CtScanner.visitCtModule(CtScanner.java:941)
	at spoon.reflect.factory.ModuleFactory$CtUnnamedModule.accept(ModuleFactory.java:96)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:178)
	at sorald.sonar.GreedyBestFitScanner.calculateBestFits(GreedyBestFitScanner.java:51)
	at sorald.Repair.repairModelWithInitializedProcessor(Repair.java:175)
	at sorald.Repair.defaultRepair(Repair.java:119)
	at sorald.Repair.repair(Repair.java:102)
	at sorald.Repair.repair(Repair.java:90)
	at sorald.cli.Cli$RepairCommand.call(Cli.java:147)
	at sorald.cli.Cli$RepairCommand.call(Cli.java:56)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at sorald.Main.main(Main.java:7)
```

**Comment by slarse** [comment]
Crash in junit4:

```
(main)[junit4] $ sorald repair --original-files-path . --rule-keys 2184
INFO  468 source files to be analyzed
INFO  468/468 source files have been analyzed
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 2
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:373)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at java.base/java.util.Collections$UnmodifiableList.get(Collections.java:1321)
	at sorald.processor.CastArithmeticOperandProcessor.getExpectedType(CastArithmeticOperandProcessor.java:79)
	at sorald.processor.CastArithmeticOperandProcessor.canRepair(CastArithmeticOperandProcessor.java:24)
	at sorald.processor.CastArithmeticOperandProcessor.canRepair(CastArithmeticOperandProcessor.java:14)
	at sorald.sonar.GreedyBestFitScanner.enter(GreedyBestFitScanner.java:77)
	at spoon.reflect.visitor.CtScanner.visitCtBinaryOperator(CtScanner.java:287)
	at spoon.support.reflect.code.CtBinaryOperatorImpl.accept(CtBinaryOperatorImpl.java:34)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:178)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:170)
	at spoon.reflect.visitor.CtScanner.visitCtBinaryOperator(CtScanner.java:291)
	at spoon.support.reflect.code.CtBinaryOperatorImpl.accept(CtBinaryOperatorImpl.java:34)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:178)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:170)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:143)
	at spoon.reflect.visitor.CtScanner.visitCtInvocation(CtScanner.java:505)
	at spoon.support.reflect.code.CtInvocationImpl.accept(CtInvocationImpl.java:46)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:178)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:170)
	at spoon.reflect.visitor.CtScanner.visitCtBinaryOperator(CtScanner.java:292)
	at spoon.support.reflect.code.CtBinaryOperatorImpl.accept(CtBinaryOperatorImpl.java:34)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:178)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:170)
	at spoon.reflect.visitor.CtScanner.visitCtBinaryOperator(CtScanner.java:291)
	at spoon.support.reflect.code.CtBinaryOperatorImpl.accept(CtBinaryOperatorImpl.java:34)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:178)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:170)
	at spoon.reflect.visitor.CtScanner.visitCtLocalVariable(CtScanner.java:532)
	at spoon.support.reflect.code.CtLocalVariableImpl.accept(CtLocalVariableImpl.java:51)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:178)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:170)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:143)
	at spoon.reflect.visitor.CtScanner.visitCtBlock(CtScanner.java:300)
	at spoon.support.reflect.code.CtBlockImpl.accept(CtBlockImpl.java:58)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:178)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:170)
	at spoon.reflect.visitor.CtScanner.visitCtMethod(CtScanner.java:566)
	at spoon.support.reflect.declaration.CtMethodImpl.accept(CtMethodImpl.java:58)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:178)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:170)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:143)
	at spoon.reflect.visitor.CtScanner.visitCtClass(CtScanner.java:336)
	at spoon.support.reflect.declaration.CtClassImpl.accept(CtClassImpl.java:58)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:178)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:170)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:143)
	at spoon.reflect.visitor.CtScanner.visitCtPackage(CtScanner.java:656)
	at spoon.support.reflect.declaration.CtPackageImpl.accept(CtPackageImpl.java:89)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:178)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:170)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:143)
	at spoon.reflect.visitor.CtScanner.visitCtPackage(CtScanner.java:655)
	at spoon.support.reflect.declaration.CtPackageImpl.accept(CtPackageImpl.java:89)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:178)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:170)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:143)
	at spoon.reflect.visitor.CtScanner.visitCtPackage(CtScanner.java:655)
	at spoon.support.reflect.declaration.CtPackageImpl.accept(CtPackageImpl.java:89)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:178)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:170)
	at spoon.reflect.visitor.CtScanner.visitCtModule(CtScanner.java:941)
	at spoon.reflect.factory.ModuleFactory$CtUnnamedModule.accept(ModuleFactory.java:96)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:178)
	at sorald.sonar.GreedyBestFitScanner.calculateBestFits(GreedyBestFitScanner.java:51)
	at sorald.Repair.repairModelWithInitializedProcessor(Repair.java:175)
	at sorald.Repair.defaultRepair(Repair.java:119)
	at sorald.Repair.repair(Repair.java:102)
	at sorald.Repair.repair(Repair.java:90)
	at sorald.cli.Cli$RepairCommand.call(Cli.java:147)
	at sorald.cli.Cli$RepairCommand.call(Cli.java:56)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at sorald.Main.main(Main.java:7)
```
