### ISSUE TITLE
Problems applying SerialVersionUidProcessor (rule 2057) to Spoon

### ISSUE THREAD

**Issue by slarse** [SpoonLabs/sorald#445]
I tried to apply the SerialVersionUidProcessor to INRIA/Spoon@2823e58503e62d863ec75fe26ddfb9bf8d900cb4, which has 9 violations, but there were two problems.

1. One NPE (this is a problem in the processor)
2. For almost every patch, the added field appears on the same line as the class header (this is a problem in the sniper printer, missing newline)

I'll look into this more tomorrow. Most likely, 1) can be fixed in Sorald, while 2) must be fixed in Spoon.

**Comment by slarse** [comment]
Confirmed that 2) is a problem in Spoon, working on a fix. See inria/spoon#3855

**Comment by slarse** [comment]
Here's the stack trace for 1)

```
java.lang.NullPointerException
	at sorald.processor.SerialVersionUidProcessor.repairInternal(SerialVersionUidProcessor.java:63)
	at sorald.processor.SerialVersionUidProcessor.repairInternal(SerialVersionUidProcessor.java:14)
	at sorald.processor.SoraldAbstractProcessor.repair(SoraldAbstractProcessor.java:87)
	at sorald.processor.SoraldAbstractProcessor.process(SoraldAbstractProcessor.java:164)
	at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:72)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:170)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:143)
	at spoon.reflect.visitor.CtScanner.visitCtClass(CtScanner.java:336)
	at spoon.support.reflect.declaration.CtClassImpl.accept(CtClassImpl.java:58)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:178)
	at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:68)
	at spoon.support.QueueProcessingManager.process(QueueProcessingManager.java:118)
	at sorald.Repair.repairModelWithInitializedProcessor(Repair.java:198)
	at sorald.Repair.defaultRepair(Repair.java:128)
	at sorald.Repair.repair(Repair.java:105)
	at sorald.Repair.repair(Repair.java:90)
	at sorald.cli.RepairCommand.call(RepairCommand.java:113)
	at sorald.cli.RepairCommand.call(RepairCommand.java:33)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at sorald.Main.main(Main.java:7)
```

**Comment by slarse** [comment]
So, the NPE is caused by the declaration not being found, which in turn is cause by the offending class actually being a subtype of `ArrayList`, and it's `ArrayList` that is serializable. The processor supposedly ignores this case, but I think that check was lost in the conversion to the new position matching, and there's no test for it.

However, I don't see a reason not to handle that case.
