### ISSUE TITLE
Targeted repair doesn't work when `--source` is a file (rather than a directory)

### ISSUE THREAD

**Issue by slarse** [SpoonLabs/sorald#480]
When the argument to `--source` is a file, targeted repair just crashes:

```
java.nio.file.FileSystemException: /home/slarse/Documents/github/work/sorald/src/test/resources/processor_test_files/1854_DeadStore/DeadInitializerInFlatBlock.java/DeadInitializerInFlatBlock.java: Not a directory
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixPath.toRealPath(UnixPath.java:860)
	at sorald.cli.RepairCommand.parseRuleViolation(RepairCommand.java:249)
	at sorald.cli.RepairCommand.parseRuleViolations(RepairCommand.java:224)
	at sorald.cli.RepairCommand.postprocessArgs(RepairCommand.java:217)
	at sorald.cli.RepairCommand.call(RepairCommand.java:100)
	at sorald.cli.RepairCommand.call(RepairCommand.java:34)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at sorald.Main.main(Main.java:7)
```

**Comment by slarse** [comment]
this strangely appears to have fixed itself. I'll just add a test case to ensure we don't get a regression.
